name: Tests

on:
    push:
        branches: [ "master", "devel" ]
    pull_request:
        branches: [ "master", "devel" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: ["3.11", "3.12"]

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Hatch
              run: pipx install hatch
            - name: Run Tests
              run: |
                  hatch test
            - name: Check Coverage
              run: |
                  hatch test --cover
            - name: Run Coveralls
              uses: coverallsapp/github-action@main
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  path-to-lcov: coverage.lcov
            - name: Run Flake8
              run: |
                  hatch run flake8 --max-line-length=120 aptly_api
            - name: Run mypy
              run: |
                  hatch run mypy --install-types --non-interactive \
                       --ignore-missing-imports --follow-imports=skip --disallow-untyped-calls \
                       --disallow-untyped-defs -p aptly_api
