name: Tests

on:
    push:
        branches: [ "master", "devel" ]
    pull_request:
        branches: [ "master", "devel" ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4

        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v5
            - name: Install Hatch
              run: pipx install hatch
            - name: Run Tests
              run: |
                  hatch test --all --cover
            - name: Lint
              run: |
                  hatch fmt --linter --check
            - name: Static Type Checking
              run: |
                  hatch run mypy:type-check
